# controller_joint_names: ['', 'head_pan', 'head_tilt', 'l_sho_pitch', 'l_sho_roll', 'l_el', 'r_sho_pitch', 'r_sho_roll', 'r_el', 'l_hip_yaw', 'l_hip_roll', 'l_hip_pitch', 'l_knee', 'l_ank_pitch', 'l_ank_roll', 'r_hip_yaw', 'r_hip_roll', 'r_hip_pitch', 'r_knee', 'r_ank_pitch', 'r_ank_roll', ]
rscuad:

  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  # Position Controllers ---------------------------------------

 
  head_pan_position: 
    type: effort_controllers/JointPositionController
    joint: head_pan
    pid: {p: 5.0, i: 0.0, d: 0.0}

  head_tilt_position:
    type: effort_controllers/JointPositionController
    joint: head_tilt
    pid: {p: 5.0, i: 0.0, d: 0.0}